### ISSUE TITLE
Possible error in Nix post

### ISSUE THREAD

**Issue by daveloyall** [ebzzry/ebzzry.github.io#1]
Hi, Rommel.

Is there an error on this line?

https://github.com/ebzzry/ebzzry.github.io/blame/b168e3d2e7b8ea04bcb232b97fdf715cbb0712c4/en/src/nix.md#L530

Should the result of `(6 / 2)` be present in the returned list?

Sorry, I don't have a Nix repl handy to test that...

**Comment by ebzzry** [comment]
Yes, that is indeed a typo. Thanks!
