### ISSUE TITLE
Error in functions and aliases

### ISSUE THREAD

**Issue by nohwnd** [ebzzry/ebzzry.github.io#5]
I think [this is incorrect](https://github.com/ebzzry/ebzzry.github.io/blob/362211555e973f9b6e9951cf55a33eaeab31addd/en/fkd/zsh-tips-1.md#functions), but I went here to get guidance how to write functions in zsh, so I might be wrong.

>alias meh="echo foo"
>simply performs text substitution. That is, when Zsh encounters the text `foo` as the first token of the command line, it replaces it with `echo foo`. Nothing more. So, running:
>meh foo
>substitutes to
>echo foo

The example alias is `meh` and the substitute is `echo foo`, shouldn't this then be: encounters `meh` as the first token. And the example would show `meh bar` -> `echo foo bar`, because the first token is replaced with the whole substitute. Or alternatively the example would be just `meh`.

**Comment by ebzzry** [comment]
Yes, that is indeed a typo. Thanks.

Fixed.
