### ISSUE TITLE
Incorrect link in nix blog post

### ISSUE THREAD

**Issue by dansvo** [ebzzry/ebzzry.github.io#9]
Hi! Thanks for your excellent nix blog post at https://ebzzry.io/en/nix/.

I noticed a small mistake: In both the English and Esperanto markdown, at the line where you mention the blogs of Luca Bruno, James Fisher, and Oliver Charles, Both Luca and James's links point to Luca's _Nix pill 1_ (https://lethalman.blogspot.com/2014/07/nix-pill-1-why-you-should-give-it-try.html). I think the link for James Fisher was probably meant to point instead to part one of James's _Nix by example_ (https://jameshfisher.com/2014/09/28/nix-by-example/)

**Comment by ebzzry** [comment]
Thank you! Fixed!
